services:
  server:
    image: ghcr.io/alicipy/lenzr-server:latest
    container_name: lenzr_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - internal
    volumes:
      - lenzr_data:/var/lib/lenzr
    security_opt:
      - no-new-privileges:true
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UPLOAD_STORAGE_PATH=${UPLOAD_STORAGE_PATH}
      - LENZR_USERNAME=${LENZR_USERNAME}
      - LENZR_PASSWORD=${LENZR_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:18.0-alpine3.22
    container_name: lenzr_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    networks:
      - internal
    security_opt:
      - no-new-privileges:true

  alembic_migrate:
    image: ghcr.io/alicipy/lenzr-server:latest
    container_name: alembic_migrate
    command: uv run alembic upgrade head
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db

networks:
  internal:

volumes:
  postgres_data:
  lenzr_data:
    driver: local
    driver_opts:
      type: none
      device: ./lenzr_data
      o: bind
